### ISSUE TITLE
Documentation for sentibank

### ISSUE THREAD

**Issue by quantdev05** [socius-org/sentibank#3]
Hi, 

Thanks for the last reply. I was also wondering whethere there are any documentations for sentibank, particularly for those processed dictionaries.

**Comment by nick-sh-oh** [comment]
Hello @quantdev05, 

I just wanted to update you that the documentation is avaliable here: [socius-org.github.io/sentibank/](https://socius-org.github.io/sentibank/). Note that the domain may be changed to doc.socius.org/sentibank in the future.
